### PR TITLE
Fixed all users online list

### PR DESCRIPTION
**Pull request by luancschmitz**
I encountered a problem when using the allOnline method. He said the $filter method was not recognized. For this I changed the allOnline method of:
```php
return $this->all()->filter->isOnline();
```

for this:
```php
return $this->all()->filter(function( $users) {
            return $users->isOnline();
});
```

### CODE REVIEW

**Comment by GabrielDeveloper** [comment]
@luancschmitz what package version and laravel version that are you using?

**Comment by luancschmitz** [comment]
Hi. I'm using version 5.3 of Laravel and version 2.0 of the package.


Enviado do Outlook<http://aka.ms/weboutlook>


________________________________
De: Gabriel Gonçalves Rodrigues <notifications@github.com>
Enviado: quarta-feira, 2 de agosto de 2017 11:51
Para: highideas/laravel-users-online
Cc: luancschmitz; Mention
Assunto: Re: [highideas/laravel-users-online] Fixed all users online list (#29)


@luancschmitz<https://github.com/luancschmitz> what package version and laravel version that are you using?

**Comment by luancschmitz** [comment]
agora vi que você é brasileiro, Eu só modifiquei o código  listado. Não conheço muito desse pull request, talvez eu tenha feito errada submissão do erro e a solução.

**Comment by GabrielDeveloper** [comment]
If you are using an version less then 5.4 on Laravel, the method filter don't work, please read the README https://github.com/highideas/laravel-users-online/tree/2.0.0 to see how works on this version:

**Pull request closed without merging**
